import React from 'react';
import Head from 'next/head';
import Headerr from './Headerr';
import Footer from './Footer';

function Layout({ title, children }) {


    return (
        <>
            <Head>
                <title>{title ? title + '-MapMak' : 'Mapmak'}</title>
                <meat name="Mapmak" content="Generated by Codico Softwares" />
                <link rel="icon" href="/fovicon.ico" />


            </Head>
            <div className='bg-white' >
                <Headerr />


                {children}

                <Footer />
            </div>
        </>
    );
}

export default Layout;